name: Java CI

on:
  push:
    branches:
      - Boot

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: dndServerTest.jar
          path: target/
        - name: Copy file to server with scp
          uses: appleboy/scp-action@v0.0.1
          env:
            HOST: ${{ secrets.HOST }}
            KEY: ${{ secrets.KEY }}
            USER: ${{ secrets.USER }}
          with:
            source: target/dndServerTest.jar
            target: /home/alexksysx/dndServerTest.jar
